---
# tasks file for my-web-page
- name: Print Linux Version (variable)
  debug:
    var: ansible_os_family

- block: # Ubuntu #
    - name: Update
      apt: update_cache=yes

    - name: Install Web Server Ubuntu
      apt: name=apache2 state=latest

    - name: Copy index.html
      copy: src={{ src_file }} dest={{ dst_file }} mode=0555
      notify: Restart_Apache_Debian

    - name: Start Web Server and Enable for Ubuntu
      service: name=apache2 state=started enabled=yes

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ignore_errors: yes

- block: # RedHat #
    - name: Update
      yum: update_cache=yes

    - name: Install Web Server Centos
      yum: name=httpd state=latest

    - name: Add Some Firewall Rules
      command: firewall-cmd --permanent --add-service=http
    - command: firewall-cmd --permanent --add-service=https
    - command: firewall-cmd --reload

    - name: Copy index.html
      copy: src={{ src_file }} dest={{ dst_file }} mode=0555
      notify: Restart_Apache_RedHat

    - name: Start Web Server and Enable for RedHat
      service: name=httpd state=started enabled=yes

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  ignore_errors: yes
