---
# tasks file for dns-server-via-docker
- block: # CentOS #
    - name: Add fqdn to hosts config file
      command: sudo bash -c 'echo "{{ server_local_addr }}  {{ server_host_name }}" >> /etc/hosts'
    - command: sudo bash -c 'echo "{{ server_remote_addr }}  {{ server_host_name }}" >> /etc/hosts'

    - name: Update
      yum:
        update_cache: yes
    - name: Install Bind-Package
      yum: name="{{item}}" state=present
      with_items:
        - bind
        - bind-utils

    - name: Set Hostname
      hostname:
        name: "{{ server_host_name }}"

    - name: Set hostname fact
      set_fact:
        ansible_fqdn: "{{ server_host_name }}"

    - name: Copy named conf file
      template:
        src: named.conf.j2
        dest: /etc/named.conf
        owner: "{{ bind_files_owner }}"
        group: named
        mode: 0660
      notify: restart named

    - name: Make named directory
      file:
        path: /etc/named
        state: directory
        owner: "{{ bind_files_owner }}"
        group: named
        mode: 0750

    - name: Copy named conf local file
      template:
        src: named.conf.local.j2
        dest: /etc/named/named.conf.local
        owner: "{{ bind_files_owner }}"
        group: named
        mode: 0640
      notify: restart named

    - name: Make zones Directory
      file:
        path: /etc/named/zones
        state: directory
        owner: "{{ bind_files_owner }}"
        group: named
        mode: 0750

    - name: Copy forward file
      template:
        src: db.forward.j2
        dest: /etc/named/zones/db.{{ domain }}
        owner: "{{ bind_files_owner }}"
        group: named
        mode: 0640
      notify: restart named

    - name: Copy reverse file
      template:
        src: db.reverse.j2
        dest: /etc/named/zones/db.{{ rev_domain }}
        owner: "{{ bind_files_owner }}"
        group: named
        mode: 0640
      notify: restart named

    - name: Open firewall port
      firewalld:
        service: dns
        permanent: true
        state: enabled
        immediate: yes

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  ignore_errors: yes

- block: # Ubuntu #
    - name: Add fqdn to hosts config file
      command: sudo bash -c 'echo "{{ server_local_addr }}  {{ server_host_name }}" >> /etc/hosts'
    - command: sudo bash -c 'echo "{{ server_remote_addr }}  {{ server_host_name }}" >> /etc/hosts'

    - name: Update
      apt:
        update_cache: yes
    - name: Install Bind-Packages
      apt:
        name: "{{ item.pkg }}"
        state: latest
      with_items: "{{ pkgs }}"

    - name: Set Hostname
      hostname:
        name: "{{ server_host_name }}"

    - name: Set hostname fact
      set_fact:
        ansible_fqdn: "{{ server_host_name }}"

    - name: Copy named conf file
      template:
        src: named.conf.j2
        dest: /etc/bind/named.conf.options
        owner: "{{ ansible_ssh_user }}"
        group: bind
        mode: 0660
      notify: restart bind9

    - name: Copy named conf local file
      template:
        src: named.conf.local.j2
        dest: /etc/bind/named.conf.local
        owner: "{{ ansible_ssh_user }}"
        group: bind
        mode: 0640
      notify: restart bind9

    - name: Copy forward file
      template:
        src: db.forward.j2
        dest: /etc/bind/db.{{ domain }}
        owner: "{{ ansible_ssh_user }}"
        group: bind
        mode: 0640
      notify: restart bind9

    - name: Copy reverse file
      template:
        src: db.reverse.j2
        dest: /etc/bind/db.{{ rev_domain }}
        owner: "{{ ansible_ssh_user }}"
        group: bind
        mode: 0640
      notify: restart bind9

    - command: echo "DNS={{ server_remote_addr }}" >> /etc/systemd/resolved.conf
      notify: restart systemd-resolved

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ignore_errors: yes
