---
# tasks file for ldap-create-user
 - block: # Ubuntu #

     - name: Add Users to ldapusers conf file
       template:
         src: ldapusers.ldif.j2
         dest: /home/{{ ansible_ssh_user }}/ldap/temp.ldif
         owner: "{{ ansible_ssh_user }}"
         group: "{{ ansible_ssh_user }}"
         mode: 0764

     - name: "Append ldapusers with content of temporary file"
       shell: cat temp.ldif >> ldapusers.ldif
       args:
         chdir: "/home/{{ ansible_ssh_user }}/ldap"
       notify: ldapadd ldapusers

     - name: "Delete temporary file"
       file:
         path: /home/{{ ansible_ssh_user }}/ldap/temp.ldif
         state: absent

   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
   ignore_errors: yes
