---
# tasks file for create_user_key_sudoers
- block: # CentOS #    
    - name: Create_User "{{ adduser_user_name }}"
      user:
        name: "{{ adduser_user_name }}"
        password: "{{ adduser_password|password_hash('sha512') }}"
        shell: /bin/bash
        groups: wheel
        state: present
      
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  ignore_errors: yes

- block: # Ubuntu #      
    - name: Create_User "{{ adduser_user_name }}"
      user:
        name: "{{ adduser_user_name }}"
        password: "{{ adduser_password|password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        state: present

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ignore_errors: yes
