---
# handlers file for ldap-create-user
- block: # Ubuntu #
    - name: ldapadd ldapusers
      command: ldapadd -x -D cn={{ cn }},dc={{ dc2 }},dc={{ dc1 }} -W -f ldapusers.ldif
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ignore_errors: yes
