---
# tasks file for nginx
      - name: "Install Nginx"
        apt:
          name: "nginx"
          state: "latest"
          update_cache: true

      - name: "Delete /var/www/html Folder"
        file:
          path: "/var/www/html"
          state: "absent"

      - name: "Copy our Site to /var/www/html Folder"
        copy:
          src: "files/html"
          dest: "/var/www/"
          owner: "wkd"
          group: "wkd"
          mode: "0644"
