---
# handlers file for keepalive-install
- block: # CentOS #
    - name: start keepalived
      systemd:
        daemon_reload: yes
        name: keepalived
        state: started

    - name: stop keepalived
      systemd:
        daemon_reload: yes
        name: keepalived
        state: stopped

    - name: restart keepalived
      systemd:
        daemon_reload: yes
        name: keepalived
        state: restarted
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  ignore_errors: yes

- block: # Ubuntu #
    - name: start keepalived
      systemd:
        daemon_reload: yes
        name: keepalived
        state: started

    - name: stop keepalived
      systemd:
        daemon_reload: yes
        name: keepalived
        state: stopped

    - name: restart keepalived
      systemd:
        daemon_reload: yes
        name: keepalived
        state: restarted
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ignore_errors: yes
