---
# tasks file for web-page-many-files
  - block: # Ubuntu #
      - name: Update
        apt: update_cache=yes

      - name: Install Web Server Ubuntu
        apt: name=apache2 state=latest

      - name: Start Web Server and Enable for Ubuntu
        service: name=apache2 state=started enabled=yes

    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    ignore_errors: yes

  - block: # RedHat #
      - name: Update
        yum: update_cache=yes

      - name: Install Web Server Centos
        yum: name=httpd state=latest

      - name: Start Web Server and Enable for RedHat
        service: name=httpd state=started enabled=yes

    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    ignore_errors: yes

  - name: Generate index.html File
    template: src={{ src_templates }}/index.j2 dest={{ dst_folder }}/index.html mode=0555
    notify:
      - Restart_Apache_RedHat
      - Restart_Apache_Debian

  - name: Copy Files
    copy: src={{ item }} dest={{ dst_folder }} mode=0555
    #copy whole directory
    with_fileglob: "{{ src_folder }}/*.*"
    notify:
      - Restart_Apache_RedHat
      - Restart_Apache_Debian
