---
# tasks file for set_fact
- name: Print Linux Version (variable)
  debug:
    var: ansible_lsb.codename

- debug:
    msg: https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/x86_64/stable/

- debug:
    msg: "Path to Source File is: {{ src_file }}"

- set_fact: from_to="{{ src_file }} to {{ dst_file }}"
- debug:
    var: from_to

- shell: uptime
  register: uptime
- debug:
    var: uptime.stdout
