---
- name: Install NTP
  hosts: linux
  become: yes
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  remote_user: USER
  
  tasks:
  - block: # CentOS #
      - name: Update
        yum:
          update_cache: yes

      - name: Installation Process
        yum: >
          name=ntp
          state=latest
      
      - name: Restart Service
        systemd:
          name: ntpd
          state: restarted
          enabled: yes

    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    ignore_errors: yes


  - block: # Ubuntu #
      - name: Update
        apt:
          update_cache: yes 
   
      - name: Installation Process
        apt: >
          name=ntp
          state=latest
      
      - name: Restart Service
        systemd:
          name: ntp
          state: restarted
          enabled: yes

    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    ignore_errors: yes
