---
# tasks file for jenkins-server-via-docker
- block: # CentOS #

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Start the jenkins docker container
      docker_container:
        image: "{{ default_container_image }}"
        name: "{{ container_name }}"
        state: started
        recreate: yes
        restart_policy: always
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - my_jenkins:/var/jenkins_home
          - update_jenkins:/usr/share/jenkins

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  ignore_errors: yes

- block: # Ubuntu #

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Start the jenkins docker container
      docker_container:
        image: "{{ default_container_image }}"
        name: "{{ container_name }}"
        state: started
        recreate: yes
        restart_policy: always
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - my_jenkins:/var/jenkins_home
          - update_jenkins:/usr/share/jenkins

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ignore_errors: yes
