---
- hosts: "{{ host }}"
  become: yes
  gather_facts: yes
  roles:
    - role: ping
      tags: [ ping ]
    - role: zabbix-agent-linux
      tags: [ zabbix-agent ]
    - role: setup
      tags: [ setup ]
    - role: add_to_sudoers
      tags: [ add_to_sudoers ]
    - role: create_user
      tags: [ create_user ]
    - role: package_install
      tags: [ package_install ]
    - role: send-ssh-key
      tags: [ send-ssh-key ]
    - role: ntp-server
      tags: [ ntp-server ]
    - role: multiple-create_user
      tags: [ multiple-create_user ]
    - role: create_user_key_sudoers
      tags: [ create_user_key_sudoers ]
    - role: my-web-page
      tags: [ install-apache-server ]
    - role: my-web-page-remove
      tags: [ delete-apache-server ]
    - role: set_fact
      tags: [ set_fact ]
    - role: loop_samples
      tags: [ loop_samples ]
    - role: web-page-many-files
      tags: [ web-page-many-files ]
