---
# tasks file for zabbix-server-via-docker
- block: # CentOS #
    - name: Create folder for docker files
      file:
        path: "{{ dst_folder }}"
        state: directory
        mode: 0775

    - name: Copy j2 docker-compose file
      template: src={{ src_templates }} dest={{ dst_folder }}/zabbix-postgres-agent-backup-docker.yml mode=0664

    - name: Copy script for backup
      copy: src={{ src_file }} dest={{ dst_folder }} mode=0664

    - name: Start zabbix-server via docker-compose
      shell: docker-compose -f {{ dst_folder }}/zabbix-postgres-agent-backup-docker.yml -p zabbix up -d

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  ignore_errors: yes

- block: # Ubuntu #
    - name: Create Folder for Docker Files
      file:
        path: "{{ dst_folder }}"       
        state: directory
        mode: 0775

    - name: Copy j2 docker-compose file
      template: src={{ src_templates }} dest={{ dst_folder }}/zabbix-postgres-agent-backup-docker.yml mode=0664

    - name: Copy script for backup
      copy: src={{ src_file }} dest={{ dst_folder }} mode=0664

    - name: Start zabbix-server via docker-compose
      shell: docker-compose -f {{ dst_folder }}/zabbix-postgres-agent-backup-docker.yml -p zabbix up -d

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ignore_errors: yes
